import asyncio
import json
import os
import sys
from datetime import datetime
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '..', 'ETL', '.env'))

# ==========================================
# PATH — Tell Python where ETL modules live
# backend/pipeline.py needs to reach ../ETL/
# ==========================================
ETL_PATH = os.path.join(os.path.dirname(__file__), '..', 'ETL')
sys.path.append(ETL_PATH)

from extraction       import extract_website_data
from router           import build_routing_map
from transformation   import clean_and_format_for_ai
from analyzer         import analyze_company
from email_generator  import generate_email
from database         import create_run

# ==========================================
# OUTPUT DIRECTORY
# All run artifacts saved here: {run_id}_analysis.json, {run_id}_email.html
# ==========================================
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'outputs')


async def run_full_pipeline(url: str, run_id: str, send_event, max_pages: int = 20):
    """
    Runs the full ETL + AI pipeline and streams progress events via send_event.

    Parameters:
        url        — prospect company URL
        run_id     — unique UUID for this run (generated by /run endpoint)
        send_event — async callback that sends a dict over the WebSocket
        max_pages  — max pages to crawl (default 20, use 5 for testing)

    Events emitted:
        {"status": "scraping",     "message": "..."}
        {"status": "routing",      "message": "..."}
        {"status": "transforming", "message": "..."}
        {"status": "analyzing",    "message": "..."}
        {"status": "generating",   "message": "..."}
        {"status": "done",         "message": "...", "data": {...}}
        {"status": "error",        "message": "..."}
    """

    try:
        os.makedirs(OUTPUT_DIR, exist_ok=True)

        # ── STEP 1: EXTRACT ───────────────────────────────────────────
        await send_event({
            "status":  "scraping",
            "message": f"Crawling website — up to {max_pages} pages..."
        })
        raw_data = await asyncio.to_thread(
            extract_website_data, url, max_pages
        )
        await send_event({
            "status":  "scraping",
            "message": f"Scraped {len(raw_data)} pages successfully"
        })

        # ── STEP 2: ROUTE ─────────────────────────────────────────────
        await send_event({
            "status":  "routing",
            "message": "Classifying pages into buckets..."
        })
        routing_map = await asyncio.to_thread(
            build_routing_map, raw_data, url
        )
        await send_event({
            "status":  "routing",
            "message": f"Routed {len(routing_map)} pages"
        })

        # ── STEP 3: TRANSFORM ─────────────────────────────────────────
        await send_event({
            "status":  "transforming",
            "message": "Building AI payload..."
        })
        ai_ready_data = await asyncio.to_thread(
            clean_and_format_for_ai, raw_data, routing_map
        )

        # Save ai_ready_payload for debugging
        payload_path = os.path.join(OUTPUT_DIR, f"{run_id}_payload.json")
        with open(payload_path, 'w', encoding='utf-8') as f:
            json.dump(ai_ready_data, f, indent=4)

        await send_event({
            "status":  "transforming",
            "message": "AI payload ready"
        })

        # ── STEP 4: ANALYZE ───────────────────────────────────────────
        await send_event({
            "status":  "analyzing",
            "message": "Sending to Groq for company analysis..."
        })
        analysis = await asyncio.to_thread(
            analyze_company, ai_ready_data
        )

        # Save analysis JSON
        analysis_path = os.path.join(OUTPUT_DIR, f"{run_id}_analysis.json")
        with open(analysis_path, 'w', encoding='utf-8') as f:
            json.dump(analysis, f, indent=4)

        await send_event({
            "status":  "analyzing",
            "message": f"Analysis complete — fit score: {analysis.get('fit_score', 'unknown').upper()}"
        })

        # ── STEP 5: GENERATE EMAIL ────────────────────────────────────
        await send_event({
            "status":  "generating",
            "message": "Writing personalized email..."
        })
        email_path, subject = await asyncio.to_thread(
            generate_email, analysis
        )

        # Copy email to outputs dir under run_id name so /email/{run_id} can serve it
        email_output_path = os.path.join(OUTPUT_DIR, f"{run_id}_email.html")
        with open(email_path, 'r', encoding='utf-8') as src:
            with open(email_output_path, 'w', encoding='utf-8') as dst:
                dst.write(src.read())

        # ── STEP 6: SAVE RUN ──────────────────────────────────────────
        create_run({
            "id":            run_id,
            "url":           url,
            "company_name":  analysis.get("company_name", "Unknown"),
            "industry":      analysis.get("industry", "Unknown"),
            "fit_score":     analysis.get("fit_score", "unknown"),
            "subject":       subject,
            "email_path":    email_output_path,
            "analysis_path": analysis_path,
            "timestamp":     datetime.now().isoformat()
        })

        # ── STEP 7: DONE ──────────────────────────────────────────────
        await send_event({
            "status":  "done",
            "message": "Pipeline complete",
            "data": {
                "run_id":       run_id,
                "company_name": analysis.get("company_name", "Unknown"),
                "industry":     analysis.get("industry", "Unknown"),
                "fit_score":    analysis.get("fit_score", "unknown"),
                "subject":      subject,
                "email_url":    f"/email/{run_id}",
            }
        })

    except Exception as e:
        # Surface the real error to the frontend — don't swallow it silently
        await send_event({
            "status":  "error",
            "message": str(e)
        })

        
